### ISSUE TITLE
Calling C Functions

### ISSUE THREAD

**Issue by andriemc** [andrei-markeev/ts2c#100]
In my opinion, the following typescript should transpile to the following C

TS:
```typescript
printf("hello world\n");
```
C:
```c
#include <stdio.h>

int main(void) {
    printf("hello world\n");
    return 0;
}
```

You may ask, why? well, That's because sometimes people will need/prefer to use functions from C (such as `printf` or file saving)

**Comment by andrei-markeev** [comment]
I agree!

With ts2c, you can actually create "target" projects that are tailored to a specific hardware target and contain all necessary definitions for this target, including `printf` or any other functions that exist on the target platform.

Example target project: https://github.com/andrei-markeev/ts2c-target-esp-idf

I don't think this behaviour should be "by default" because it's not a given that `printf` references the `stdio.h` function and not some js function from your code.
