### ISSUE TITLE
scanf?

### ISSUE THREAD

**Issue by Meldiron** [andrei-markeev/ts2c#17]
How can I do scanf using this?

**Comment by andrei-markeev** [comment]
No good support for scanf yet.

ts2c doesn't perform validation on the existence of a called function, so simply adding `scanf` call into the code will work:

![image](https://user-images.githubusercontent.com/5181724/38461364-584f2862-3ad6-11e8-90f1-728d00c52613.png)

However, the bigger problem is that there's no way currently to define a buffer, especially string buffer as this is obviously one of the primary use cases. All strings are essentially `const char *`, so writing into them will not work.

Example:
![image](https://user-images.githubusercontent.com/5181724/38461332-b60ed520-3ad5-11e8-8353-f061850abe98.png)

Obviously this will lead to `Segmentation fault`.

Anyway thanks for the heads-up, I will think of how to incorporate `scanf` into current design with time. I have to say this cannot be considered a primary use case (because main target is microcontrollers and common IoT scenarios).

**Comment by andrei-markeev** [comment]
It should be possible to do this starting from 2.2.9.
More or less any C function can be linked into JS code if a corresponding definition is created.

Example: [tests/statements/import_target.ts](https://github.com/andrei-markeev/ts2c/blob/master/tests/statements/import_target.ts)
