### ISSUE TITLE
ES6 module

### ISSUE THREAD

**Issue by zaoqi** [andrei-markeev/ts2c#27]
```js
function id(x){
  return x;
}
export {id};
```

```c
void id(void x)
{
    return x;

}

int main(void) {
    /* Unsupported node: export {id}; */;

    return 0;
}
```

**Comment by andrei-markeev** [comment]
For now I'm working on ES3 support only, ES6 support is still quite far in the future. Please see [COVERAGE.md](https://github.com/andrei-markeev/ts2c/blob/master/COVERAGE.md).

Modules support for external dependencies is definitely in the roadmap, but it's not yet decided if it will be commonjs or TS modules syntax.

**Comment by andrei-markeev** [comment]
Some news:
1. I added support for importing external modules (see example in project [ESP-IDF target for TS2C](https://github.com/andrei-markeev/ts2c-target-esp-idf)).
2. Basic version of importing local files also works more or less fine. If you import other .ts files into your main .ts file which you compile with TS2C, all those files will be merged into a single .c file.
This simple test passes without issues: [tests/statements/import.ts](https://github.com/andrei-markeev/ts2c/blob/master/tests/statements/import.ts), but there might be some edge cases where it doesn't work.

Important note though, that while it works very well in Node.js (Typescript does all module resolution and fetching automatically it turned out), but making it work in browser might be a much harder problem to solve. I'm going to postpone further work on this topic for now, and switch back to ES3 language features implementation.
