### ISSUE TITLE
IIFE conversion?

### ISSUE THREAD

**Issue by CrazyPython** [andrei-markeev/ts2c#28]
```js
let name = () => {
    declarations;
    return rvalue;
}()
```
to
```c
type name;
{
    declarations;
    name = rvalue;
}
```

**Comment by andrei-markeev** [comment]
Thanks for the idea!

One thing though: if there are multiple returns inside IIFE, that makes things a bit ugly, because we would have to break from the block using `goto` in that case.

In overall, I think the idea is sound, but I would propose to only optimize simple IIFEs with that approach - ones that don't return values and don't have any return statements inside.

**Comment by andrei-markeev** [comment]
Some news on this one.

I spent few hours last night and implemented an optimization that worked with `return`-s, but it turned out to be too complex and too ugly. Typescript makes AST patching very cumbersome by not supporting changing `parent`, `pos` and `end` of the node. I was so unhappy with the end result and amount of dirty hacking I had to do, I decided it was not worth including this ugly piece of code into the codebase.

I am starting to think of changing from using Typescript to some other parser or even create my own tailored parser, because Typescript brings a lot of overhead: it's huge, has a lot of features that TS2C will never need, has a really noticeable startup lag people are complaining about, etc.

I will not implement further optimizations that require non-trivial AST patching for now. However, simple IIFE optimization has been implemented already several years ago, so I will close this ticket as completed.
