### ISSUE TITLE
Prefix increment operator not working in for loops

### ISSUE THREAD

**Issue by paul-go** [andrei-markeev/ts2c#32]
Some of us use 2-statement style `for` loops using the prefix increment operator. These don't seem to compile, although in COVERAGE.md it says that prefix increment operators are implemented. Example:

```
var x: number[] = [];
for (var i = -1; ++i < x.length;)
{
  console.log(i);
}
```

(Side note: This is a very interesting project. Years ago I posted [this](https://github.com/Microsoft/TypeScript/issues/9202) on the TypeScript forum and have been following many TypeScript => !JavaScript compiler projects.)

**Comment by andrei-markeev** [comment]
Hi, the actual reason was empty increment part of the for loop. Now fixed and your example compiles fine.

> Years ago I posted this on the TypeScript forum
Yeah I actually saw this post and it was part of inspiration to create this project, all those super-experts telling that it is not possible 😃 Still convinced that everything can be transpiled except `eval` and `new Function`.
