### ISSUE TITLE
Cannot determine variable type from source null

### ISSUE THREAD

**Issue by zaoqi** [andrei-markeev/ts2c#38]
```js
function ERROR() {
    throw "...";
}
function ASSERT(x) {
    if (!x) {
        return ERROR();
    }
}
```

```
void ASSERT(/* Cannot determine variable type from source null*/ x)
{
    if (!x)
        return ERROR();

}
```

**Comment by andrei-markeev** [comment]
If you will call this function somewhere, ts2c will be able to determine the type. It is designed for practical usage, and currently not really suited for making this kind of library code.

For example this is transpiled without errors:
```ts
function ERROR() {
    throw "...";
}
function ASSERT(x) {
    if (!x) {
        return ERROR();
    }
}

ASSERT(0)
```

Of course I can make a default type assumption, but there are some issues with that. For default type, there are two main candidates: a pointer (`void *`) and a universal variable (`struct js_var`). But the first will usually be totally impractical, and the second will blow the resulting code quite a bit because then it would need to transpile at least the minimum amount of helper functions and data structures that are required for universal data type.
