### ISSUE TITLE
Destructuring function arguments result in TypeError

### ISSUE THREAD

**Issue by OyvindSabo** [andrei-markeev/ts2c#39]
This works:
```
function multiplyByTwo(arg){
  return 2 * arg;
}
```
This does not work:
```
function multiplyByTwo({ arg }){
  return 2 * arg;
}
```
I get the following error:
```
Transpilation failed. TypeError: Cannot read property 'name' of undefined
```
With this error in the console:
```
Uncaught TypeError: Cannot read property 'name' of undefined
    at TypeHelper.generateStructure (ts2c.bundle.js:6618)
    at TypeHelper.convertType (ts2c.bundle.js:6601)
    at TypeHelper.getCType (ts2c.bundle.js:6245)
    at ts2c.bundle.js:6519
    at Array.forEach (<anonymous>)
    at TypeHelper.resolveTypes (ts2c.bundle.js:6519)
    at TypeHelper.inferTypes (ts2c.bundle.js:6515)
    at newConstructor.CProgram (ts2c.bundle.js:2713)
    at new newConstructor (ts2c.bundle.js:5608)
    at Object.transpile (ts2c.bundle.js:6805)
```

It's not important to me that destructuring arguments work, but I couldn't find any info about it in [COVERAGE.md](https://github.com/andrei-markeev/ts2c/blob/master/COVERAGE.md). It would save some time debugging if it was added to the coverage document.

**Comment by andrei-markeev** [comment]
Destructuring is a feature of ES6, same as for example arrow functions, const/let, template strings, default parameter values, for..of, etc.

For now I am still working on ES3 support, correspondingly COVERAGE.md only lists features from ES3 spec.

The workaround is of course to transpile from ES6 to ES3 using babel or typescript, but the ultimate goal of this project is to support ES6 features directly (because in this case it is possible to produce a more readable output).

Actually, at least two features from ES6 are already supported, namely for..of and import (the latter will only work in Node.js environment though, not in the browser playground).

But in general, ES6 support is still quite far in the future, so I will close this issue as not relevant for now.
