### ISSUE TITLE
Compiling TypeScript to C via WebAssembly

### ISSUE THREAD

**Issue by jarble** [andrei-markeev/ts2c#72]
I found two compilers that could be used to convert TypeScript to C:

* [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) compiles TypeScript to WebAssembly.
* [Wasmdec](https://github.com/wwwg/wasmdec) decompiles WebAssembly to C source code.

Would it be feasible to compile TypeScript programs to WebAssembly using AssemblyScript, and then de-compile them to C using Wasmdec?

**Comment by andrei-markeev** [comment]
There are many solutions out there to get C code out of js code.

For example, long before I started ts2c, I experimented with ts2hx, and I know there are similar approaches like js -> lua -> c, js -> python -> c and so on. But all of them are compilers rather than transpilers. They produce mostly unreadable code, or otherwise use huge runtimes (e.g. "Hello world" program compiled via ts2hx produces ~1Mb exe file).

This project is about transpiling TS, and getting highly optimized C code as a result. Very different approach.
