### ISSUE TITLE
Using C++ instead of C?

### ISSUE THREAD

**Issue by 2pichar** [andrei-markeev/ts2c#86]
As I've been browsing the repository, I've been wondering why this is using C instead of C++. By using C++, we could use all of the features of C with the addition of classes, which would make several JS/TS features easier to implement. What's the reasoning behind using C?

**Comment by andrei-markeev** [comment]
Hi, the reason is that this project is, potentially, for embedded devices also: https://github.com/andrei-markeev/ts2c#rationale

**Comment by 2pichar** [comment]
This doesn't explain why this project uses C instead of C++. Resource-wise, wouldn't the two be approximately the same?

**Comment by andrei-markeev** [comment]
By "C++ is not an option", I mean that C++ compilers and other tools (debugger, IDE, etc.) for many embedded systems are either not available or available at additional cost.

Some more considerations mentioned e.g. here, even though some of them can be solved because the code is generated so it can be generated in a specific way that aboids the mentioned problems:
https://stackoverflow.com/questions/812717/is-there-any-reason-to-use-c-instead-of-c-for-embedded-development

**Comment by 2pichar** [comment]
I think I get it now. I was just thinking that if this project transpiled TS to C++, then we could implement `instanceof`, classes, and basically everything else in ES3-6 a lot easier.
